### ISSUE TITLE
I am very confused about your paper.

### ISSUE THREAD

**Issue by qhdqhd** [gmum/MultiPlaneNeRF#1]
In your paper, you directly input the RGB and coordinates of the two-dimensional projection into the MLP network. In my opinion, this seems to be a simplified version of pixelnerf.

Can the size of MLP be reduced through such a simple operation? Your paper did not tell us how much MLP has decreased. How much faster has the training speed increased?

You claim that your method can reduce the number of images, but you have not provided any relevant experiments or compared it with pixelnerf or other few-shot methods.

**Comment by Ideefixze** [comment]
> In my opinion, this seems to be a simplified version of pixelnerf.

The pixelnerf represents of the model which uses existing images and transfers images through the large backbone. 
Their method is mainly designed to train NeRF from a few (even one) images. MultiPlaneNeRF works directly on images and in practice uses few fully connected layers similar to classical NeRF. In our opinion, such models are in different classes. When we use a large backbone, we can build a high-level representation that does most of the work in the process and allows training from only a few images. In practice, MultiPlane NeRF is more similar to TriPlane NeRF, which extracts information from trainable representation. Our model works similarly, but we use nontrainable representation. Our model works on existing images, so we do not need a large feature extractor. But we are not able to train from a few images. Moreover, we can aggregate information from planes, similar to TriPlane.

> Can the size of MLP be reduced through such a simple operation? Your paper did not tell us how much MLP has decreased. How much faster has the training speed increased?

Our training process for NeRF Synthetic dataset scenes has used all 100 images included in that dataset. Meaning we had 100 planes that were sampled at every point.
For single-scene optimization, our neural network is very similar to classical NeRF. The main difference is within the input. An RGB color vector and pixel position were included for each image in a training dataset. So, for 100 images in \our{}, a $3\times100 + 2\times100$ input parameter is needed.
This input is then processed by linear layers, each followed by a ReLU activation function. In detail, the output for layer size for the first section of the network is: $[(500, 256), (256, 256), (256, 256), (256, 256), (256, 256)]$, then skip layers occurs. To the output of the previous section, an input is concatenated, and we repeat the process for another layer of output size $[(256 + 500, 256), (256, 256), (256, 256), (256, 256)]$. We included the skip layer once before the $\sigma$ output one last time $[(256 + 500), 128), (128, 1)]$. Direction angles with positional encoding (in total $27$) are also added before RGB layers of size $[(256 + 500 + 27, 256), (256, 256), (256, 3)]$.

> You claim that your method can reduce the number of images, but you have not provided any relevant experiments or compared it with pixelnerf or other few-shot methods.

In our paper, we do not claim that we can train from a few images. We only show how the performance of the model change when we use a various number of images for representation. In practice, MultiPlane NeRF and pixelnerf are dedicated to different tasks. Pixelnerf is dedicated to few-shot training. MultiPlane NeRF is a NeRF-based model that use non-trainable representation. But we need relatively many images. Thanks to this non-trainable representation we obtain generalization properties.

**Comment by qhdqhd** [comment]
Thank you for your quick reply.

In my opinion, your current experimental results are not convincing enough. I look forward to your paper being further improved.
